"""empty message

Revision ID: 6d8f5b6b4710
Revises: 9ac1ddfcee24
Create Date: 2023-03-12 16:30:26.131374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d8f5b6b4710'
down_revision = '9ac1ddfcee24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match', 'secret_key',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match', 'secret_key',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
