"""empty message

Revision ID: a73f40a344a5
Revises: 6d8f5b6b4710
Create Date: 2023-03-13 03:53:02.364251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a73f40a344a5'
down_revision = '6d8f5b6b4710'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('map', sa.Text(), nullable=False))
    op.drop_column('match', 'selected_map')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('selected_map', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('match', 'map')
    # ### end Alembic commands ###
